#  docker-compose.prod.yml

version: "3.9"

services:
  service-a:
    build:
      context: .
      dockerfile: app/backend/service-a/Dockerfile
      target: builder # Use production stage (not dev!)
    image: service-a:latest
    container_name: service-a-prod
    ports:
      - "8080:8080"
    restart: always
    # No volumes - code is baked into image
    # No hot-reload - this is production

  service-b:
    build:
      context: .
      dockerfile: app/backend/service-b/Dockerfile
      target: builder # Use production stage (not dev!)
    image: service-b:latest
    container_name: service-b-prod
    ports:
      - "8081:8081"
    restart: always
    # No volumes - code is baked into image
    # No hot-reload - this is production
