[build]
  cmd = "go run ." 
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]

[paths]
  # Wichtige Verzeichnisse zum Überwachen
  include = ["api_gateway", "modules/user_service", "shared"]

