root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/runner"
  cmd = "go build -o ./tmp/runner ."
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  poll = true              
  poll_interval = 500      
  stop_on_error = true
  send_interrupt = true   
  kill_delay = 5 

[watch]
  include_dir = ["./", "../../../shared/go"]

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true