# config/promtail.yaml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
    
    # ✅ JSON Parsing Pipeline
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            timestamp: time
      
      # ✅ Level als Label (für Farben!)
      - labels:
          level:
          service:
      
      # ✅ Timestamp verwenden
      - timestamp:
          source: timestamp
          format: RFC3339